/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDiaryRouteImport } from './routes/_app.diary'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDiaryRoute = AppDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diary': typeof AppDiaryRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diary': typeof AppDiaryRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/diary': typeof AppDiaryRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diary' | '/history' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diary' | '/history' | '/home'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/diary'
    | '/_app/history'
    | '/_app/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diary': {
      id: '/_app/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppDiaryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiaryRoute: typeof AppDiaryRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiaryRoute: AppDiaryRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
